### PR TITLE
fix: table formatting

### LINKED ISSUE #17: Fix table parsing
Moving to the larger data set causes issues with the rendering of the table. The `if (nrow() == 1)` is causing situations with a single row of all NA values to break,

### PR DESCRIPTION
**Pull request by jr-nicola**
Since updates to {tfpscanner} (from Erik's side I believe), csv files has data properly stored in rows and columns instead of all stored in cell A1. Most of the `reformat_table()` function is now unnecessary. The edits here now just checks if the first column is simply row numbers and, if so, removes it.

Closes #17

### CODE REVIEW

File: R/utils.R [hunk 1]
```diff
@@ -60,29 +60,10 @@ get_all_files = function(cluster_choice) {
...
-                      y = stringr::str_trim(.data$y)) %>%
-        `colnames<-`(.[1, ]) %>% # nolint
-        dplyr::slice(-1)
-    } else {
-      output = tibble::tibble(x = "Nothing to display")
-    }
-  } else {
-    output = janitor::clean_names(table_to_display,
-                                  case = "title")
+  if (all(unlist(table_to_display[,1]) == seq_len(nrow(table_to_display)))) {
```
Comment (russHyde) [inline R/utils.R:63]:
```suggestion
  if (all(table_to_display[[1]] == seq_len(nrow(table_to_display)))) {
```
From the description, `table_to_display` should be a data.frame or tibble. df[[1]] has a consistent behaviour between tibbles and data.frames, in a way that df[, 1] doesn't.

**Review by russHyde — COMMENTED** [review]
I've a dded a slightly neater way to extract a vector from the first column, but otherwise it looks fine.
